GET http://localhost:3000/open/logs



###

POST http://localhost:3000/url
content-type: application/json

{
    "name":"opena","url":"https://www.google.com"
}

####

POST http://localhost:3000/open/deactivate
