const express = require('express');
const db = require('./db/config');
require('dotenv').config();
const app = express();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
const router = require('./routes/pages');
app.use('/',router);
app.set('view engine','ejs');
app.use(express.static(__dirname + '/web'));
db.connect().then(()=>{console.log('db connected')}).catch(error=>{console.log(error.message)});
app.listen(process.env.PORT,()=> console.log('server started'));